@startuml BaseDeriviedClassDiagram
!theme plain
skinparam monochrome true
skinparam classAttributeIconSize 0
skinparam backgroundColor white
skinparam classBackgroundColor white
skinparam classBorderColor black
skinparam arrowColor black

class Animal {
    # species: String
    + make_sound(sound: String): void
}

class Bird {
    - wing_span_: Real
    + can_fly(): Boolean
}

class Elephant {
    + use_trunk(): void
}

Animal <|-- Bird : + public
Animal <|-- Elephant : + public


@enduml
